server:
  port: 8081
spring:
  web:
    resources: # 指定静态资源的路径
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  devtools:
    restart:
      enabled: true
  mail:
    username: codecodeup@163.com  #修改为自己的邮箱
    password: QKRIUAMMLHGGYEGB  #授权码（第三步中生成的授权码）
    host: smtp.163.com  #发送邮件的服务主机
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl: 
            enable: true  #开启ssl安全
  servlet:
    multipart:
      max-file-size: 200MB #单个文件上传大小
      max-request-size: 600MB #连续上传文件大小
            
  datasource:
    username: root 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/issue?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    
mybatis:
  # 指定全局配置文件位置
  #config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:Mapper/*.xml  
  type-aliases-package: com.ibm.issue

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    


#设置文件路径
web:
  upload-path: D:/pic/
  user-path: D:/pic/user/
  issue-path: D:/pic/issue/



  
logging:
   level:
     com.ibm.springboot.controller.LoggingController: trace  #设置输出级别

# 1.不指定路径时会在当前项目下生成springboot.log日志
# 2.可以指定完整的路径,如：D:/springboot.log
   file: springboot.log
  

    